[package]
name = "autd3-firmware-test"
version = "7.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
autd3 = { path = "autd3/autd3" }
autd3-link-soem = { path = "autd3/autd3-link-soem" }
autd3-link-twincat = { path = "autd3/autd3-link-twincat" }
autd3-link-simulator = { path = "autd3/autd3-link-simulator" }
colored = "2.1.0"
tokio = { version = "1.37.0", features = ["full"] }
