[package]
name = "autd3-firmware-test"
version = "11.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
autd3 = "32.0.1"
autd3-link-soem = "32.0.1"
autd3-link-twincat = "32.0.1"
autd3-link-simulator = { version = "32.0.1", features = ["blocking"] }
colored = "3.0.0"
tracing-subscriber = "0.3.19"
tracing = "0.1.40"
